spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test # H2 메모리 데이터베이스를 사용하도록 설정
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create # Hibernate에게 데이터베이스 스키마를 자동으로 업데이트하도록 지시
    database-platform: org.hibernate.dialect.H2Dialect # H2 데이터베이스용 Hibernate 디아렉트 설정

logging:
  level:
    root: info # 로그 레벨 설정
   # org.hibernate.SQL: debug # Hibernate SQL 로깅 활성화
