spring:
  datasource:
    url: jdbc:mysql://opendhousedb.czwu68c0443c.us-east-2.rds.amazonaws.com:3306/opendhousedb?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: kan0202
    password: sky2002369

  jpa:
    hibernate:
      ddl-auto: create # Hibernate에게 데이터베이스 스키마를 자동으로 업데이트하도록 지시
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect

logging:
  level:
    root: info # 로그 레벨 설정
   # org.hibernate.SQL: debug # Hibernate SQL 로깅 활성화
